[package]
name = "filecoin-f3-lightclient"
version = "0.1.0"
description = "Light client functionality for F3 fast finality protocol, allowing validation of F3 finality certificates without running a full F3 node"
authors.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
filecoin-f3-blssig = { workspace = true }
filecoin-f3-certs = { workspace = true }
filecoin-f3-gpbft = { workspace = true }
filecoin-f3-rpc = { workspace = true }

anyhow.workspace = true
base64 = { workspace = true }
hex.workspace = true
keccak-hash.workspace = true
tokio.workspace = true
